### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/pattern-strategy-regnard-marchand#1]
Bonjour, 

Serait-il possible d'avoir une revue de code ?

**Comment by k33g** [comment]
Bonjour @AwaitingIrindul j'aimerais des cas d'usages concrets (vraie vie) pour le paragraphe **Donnez 3 autres cas d'utilisation du pattern Strategy** 😄

**Comment by AwaitingIrindul** [comment]
Bonjour @k33g, 
- Une voiture avec différentes mode de conduite, on aura par exemple une strategy Tesla, qui conduira seule, une strategy Sportive avec une conduite manuelle mais commandes aux palletets ect...
- Pour de l'encryption, selon la taille du message on peut appliquer différentes strategy comme par exemple une strategy ou des parties du messages sont mise en cache et une strategy qui va utiliser le disque dur
- Un simple jeu vidéo, ou selon l'état/les actions du joueur, un PNJ pourrait avoir différents comportements.

S'il faut un peu plus de detail concernant l'implémentation nous pouvons détailler un peu plus.

**Comment by k33g** [comment]
@AwaitingIrindul ok, mais mettez à jour le rapport

**Comment by AwaitingIrindul** [comment]
Bonjour, 

ça à été ajouté :)

**Comment by AwaitingIrindul** [comment]
Bonjour @k33g, peut-on fermer cette issue ou d'autres modifications doivent être apportés ?
